[package]
name = "rs_ml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rs_ml"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
supervised_algos = { path = "../supervised_algos" }
